=== juanmagape/digitech-general/lenguajedemarcas/0373-ae010/cataleg-pelis/pelis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="pelis">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="peli" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titol" type="xs:string"/>
              <xs:element name="director" type="xs:string"/>
              <xs:element name="durada" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== juanmagape/digitech-general/lenguajedemarcas/0373-ae010/cataleg-pelis/pelis.xml
<?xml version="1.0" encoding="UTF-8"?>
<pelis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="pelis.xsd">
    <peli>
        <titol>Minecraft The Movie</titol>
        <director>Chicken Jockey</director>
        <durada>190</durada>
    </peli>
    <peli>
        <titol>Demon Slayer</titol>
        <director>Jhon Pork</director>
        <durada>203</durada>
    </peli>
    <peli>
        <titol>FNAF: The movie</titol>
        <director>Meowl</director>
        <durada>180</durada>
    </peli>
</pelis>
