=== juanmagape/digitech-general/lenguajedemarcas/casosdedades-xsd/cas1/cas1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="jugadors">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jugador" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="edat" type="xs:integer"/>
              <xs:element name="equip" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== juanmagape/digitech-general/lenguajedemarcas/casosdedades-xsd/cas1/cas1.xml
<?xml version="1.0" encoding="UTF-8"?>
<jugadors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="cas1.xsd">
  <jugador>
    <nom>Àlex</nom>
    <edat>25</edat>
    <equip>Vermells</equip>
  </jugador>
  <jugador>
    <nom>Marta</nom>
    <edat>22</edat>
    <equip>Blaus</equip>
  </jugador>
  <jugador>
    <nom>Pol</nom>
    <edat>28</edat>
    <equip>Grocs</equip>
  </jugador>
  <jugador>
    <nom>Laia</nom>
    <edat>24</edat>
    <Equip>Vermells</equip>
  </jugador>
</jugadors>
