=== juanmagape/digitech-general/lenguajedemarcas/xsd-practica-guiada/llibres.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="llibres">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="llibre" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titol" type="xs:string"/>
              <xs:element name="autor" type="xs:string"/>
              <xs:element name="preu" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== juanmagape/digitech-general/lenguajedemarcas/xsd-practica-guiada/llibres.xml
<?xml version="1.0" encoding="UTF-8"?>
<llibres
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="llibres.xsd">
  <llibre>
    <titol>Clean Code</titol>
    <autor>Robert C. Martin</autor>
    <preu>32</preu>
  </llibre>
  <llibre>
    <titol>Effective Java</titol>
    <autor>Joshua Bloch</autor>
    <preu>45</preu>
  </llibre>
</llibres>
