=== juanmagape/digitech-general/lenguajedemarcas/0373-ae010/gestio-esdeveniments/esdeveniments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="esdeveniments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="esdeveniment" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="data" type="xs:date"/>
              <xs:element name="lloc" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== juanmagape/digitech-general/lenguajedemarcas/0373-ae010/gestio-esdeveniments/esdeveniments.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="esdeveniments.xsl"?>

<esdeveniments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="esdeveniments.xsd">
    <esdeveniment>
        <nom>Caiguda del Mur de Berlín</nom>
        <data>1989-11-09</data>
        <lloc>Berlín, Alemanya</lloc>
    </esdeveniment>
    <esdeveniment>
        <nom>Primera arribada a la Lluna</nom>
        <data>1969-07-20</data>
        <lloc>Luna</lloc>
    </esdeveniment>
    <esdeveniment>
        <nom>Declaració d'Independència dels Estats Units</nom>
        <data>1776-07-04</data>
        <lloc>Filadèlfia, EUA</lloc>
    </esdeveniment>
</esdeveniments>
